version: "3.9"

services:
  db:
    image: postgres:12.1
    container_name: database
    ports:
    - "5434:5432"
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spell
  api:
    build:
      context: .
      target: DevServer
    container_name: api
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - .:/code
    stdin_open: true
    tty: true
    restart: always
  orion-spell:
    container_name: orion-spell
    build:
      context: .
      target: orion
    ports:
    - "4200:4200"
    command: "prefect orion start"
    environment:
      PREFECT_ORION_API_HOST: 0.0.0.0
      PREFECT_API_URL: http://host.docker.internal:4200/api
  agent-spell:
    container_name: agent-spell
    command: "prefect agent start -q default"
    volumes:
      - .:/code
    build:
      context: .
      target: agent
    depends_on:
      - orion-spell
    env_file: .env
    environment:
      PREFECT_API_URL: http://orion-spell:4200/api
