apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-env
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
    DATABASE_HOST:     {{ .Values.database.host     | quote }}
    DATABASE_USER:     {{ .Values.database.username | quote }}
    DATABASE_PASSWORD: {{ .Values.database.password | quote }}
    DATABASE_DATABASE: {{ .Values.database.database | quote }}
    GLITCHTIP_DNS:     {{ .Values.glitchtip.dns     | quote }}
    PREFECT_API_URL:   {{ .Values.prefect.api       | quote }}