# Generated by Django 4.1.4 on 2022-12-27 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Summoner",
            fields=[
                (
                    "id",
                    models.CharField(max_length=120, primary_key=True, serialize=False),
                ),
                ("account_id", models.CharField(max_length=120)),
                ("puuid", models.CharField(max_length=120, unique=True)),
                ("name", models.CharField(max_length=40)),
                ("profile_icon_id", models.IntegerField()),
                ("level", models.IntegerField()),
                ("revision_date", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Queue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("league_id", models.CharField(max_length=120, unique=True)),
                ("type", models.CharField(max_length=40)),
                ("tier", models.CharField(max_length=40)),
                ("rank", models.CharField(max_length=40)),
                ("wins", models.IntegerField()),
                ("losses", models.IntegerField()),
                ("points", models.IntegerField()),
                ("is_veteran", models.BooleanField()),
                ("is_active", models.BooleanField()),
                ("is_noob", models.BooleanField()),
                ("hotstreak", models.BooleanField()),
                (
                    "summoner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="queues",
                        to="league.summoner",
                    ),
                ),
            ],
        ),
    ]
