# Generated by Django 4.1.4 on 2022-12-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queue",
            name="league_id",
            field=models.CharField(max_length=120),
        ),
    ]
