image:
  repository: lukeinstruct/spell
  tag: latest
  pullPolicy: Always
  imagePullSecrets: []

configmap:
  data:
    DEBUG: True
    SECRET_KEY: "!!!SET SECRET_KEY!!!"
    DJANGO_SETTINGS_MODULE: config.settings
    DATABASE_ENGINE: "django.db.backends.postgresql"
    PYTHONDONTWRITEBYTECODE: 1
    PYTHONUNBUFFERED: 1

database:
  host: postgres
  username: postgres
  password: postgres
  database: postgres

djangoServer:
  replicaCount: 1

  command: ["./start-dev.sh"]

  podSecurityContext: {}

  securityContext: {}

  service:
    type: ClusterIP
    port: 8000

  ingress:
    enabled: true
    annotations: {}

    path: /
    pathType: ImplementationSpecific
    hosts:
      - lucasvinicius.site

    tls: []

  nodeSelector: {}
  tolerations: []
  resources: {}
  affinity: {}

glitchtip:
  dns: https://key@glitchtip.lucasvinicius.site/1

prefect:
  api: http://prefect-service.prefect:4200/api